version: "2"
services:
  node:
    container_name: tonic
    image: "node:12"
    user: "node"
    stdin_open: true
    tty: true
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    command: "npm test"
